import { NextRequest } from "next/server";
import { z } from "zod";
import { apiSuccess, apiError } from "@/lib/api/response";
import { validateBody } from "@/lib/api/validation";
import { getAuthenticatedUser } from "@/lib/api/auth-middleware";
import { checkRateLimit } from "@/lib/api/rate-limit";
import { getSystemPromptForMode, AITaskMode } from "@/lib/ai/openai-client";
import { supabaseAdmin } from "@/lib/supabase/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

export const maxDuration = 60; // 60s timeout for AI generation

const aiRequestSchema = z.object({
  prompt: z.string().min(1, "Prompt is required"),
  mode: z
    .enum([
      "code_review",
      "hint_generator",
      "time_complexity",
      "space_complexity",
      "dry_run",
      "bug_finder",
      "interview_generator",
      "resume_reviewer",
      "learning_roadmap",
      "contest_performance",
      "project_feedback",
      "teacher_assistant",
      "chat",
    ])
    .default("chat"),
  code: z.string().optional(),
  language: z.string().optional(),
  problemTitle: z.string().optional(),
  messages: z
    .array(
      z.object({
        role: z.enum(["system", "user", "assistant"]),
        content: z.string(),
      })
    )
    .optional(),
  stream: z.boolean().default(false),
});

export async function POST(req: NextRequest) {
  const user = await getAuthenticatedUser(req);
  const userId = user?.id;

  const ip = req.headers.get("x-forwarded-for") || "client-ip";
  const rateKey = userId ? `ai:${userId}` : `ai:${ip}`;

  // Rate limit: 50 requests per hour per user
  const rate = checkRateLimit(rateKey, 50, 3600000);
  if (!rate.success) {
    return apiError("Daily Ido AI quota reached (50 requests/hour). Please try again later.", 429);
  }

  const { data: body, error: valError } = await validateBody(req, aiRequestSchema);
  if (valError) return apiError("Validation failed", 400, valError);

  const { prompt, mode = "chat", code, language, problemTitle, messages, stream } = body!;
  const systemPrompt = getSystemPromptForMode(mode as AITaskMode);

  // Load Gemini API Key from environment
  const geminiApiKey =
    process.env.GEMINI_API_KEY ||
    process.env.NEXT_PUBLIC_GEMINI_API_KEY;

  console.log("Using Gemini API Key:", geminiApiKey ? "✔ Present" : "❌ Missing");

  if (!geminiApiKey) {
    return apiError("GEMINI_API_KEY is not configured in server environment.", 500);
  }

  try {
    const genAI = new GoogleGenerativeAI(geminiApiKey);
    // Use gemini-1.5-flash model
    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
      systemInstruction: systemPrompt,
    });

    let fullPrompt = prompt;
    if (code) {
      fullPrompt += `\n\n\`\`\`${language || "text"}\n${code}\n\`\`\``;
    }
    if (problemTitle) {
      fullPrompt = `[Problem: ${problemTitle}]\n${fullPrompt}`;
    }

    if (stream) {
      const streamResult = await model.generateContentStream(fullPrompt);
      const encoder = new TextEncoder();

      const readable = new ReadableStream({
        async start(controller) {
          for await (const chunk of streamResult.stream) {
            const text = chunk.text();
            if (text) {
              controller.enqueue(encoder.encode(text));
            }
          }
          controller.close();
        },
      });

      return new Response(readable, {
        headers: {
          "Content-Type": "text/event-stream",
          "Cache-Control": "no-cache, no-transform",
          Connection: "keep-alive",
        },
      });
    }

    const result = await model.generateContent(fullPrompt);
    const reply = result.response.text() || "No response generated by Ido AI.";

    if (userId) {
      await supabaseAdmin.from("coding_activity").insert({
        user_id: userId,
        activity_type: `AI ${(mode || "chat").toUpperCase()}`,
        description: `Used Ido AI (${mode}): ${prompt.substring(0, 50)}...`,
        xp_earned: 5,
      });
    }

    return apiSuccess({ reply, mode }, "Ido AI response generated successfully");
  } catch (err: any) {
    console.error("Gemini API call error:", err);
    return apiError(`Gemini AI Generation Error: ${err.message}`, 500);
  }
}
