-- CampusCode Original Problem Set (CCPS v1.0) - Batch 2 (CC051 - CC100)

INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000051', 'CC051: Campus Library Binary Search Locator', 'campus-library-binary-search-locator', 'EASY', 'At Sarhad College, compute the optimal configuration for **Campus Library Binary Search Locator**. Given $N$ input records, write an algorithm using Binary Search to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000052', 'CC052: Student Placement Salary Sorter', 'student-placement-salary-sorter', 'EASY', 'At Sarhad College, compute the optimal configuration for **Student Placement Salary Sorter**. Given $N$ input records, write an algorithm using Sorting to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000053', 'CC053: Exam Prefix Score Accumulator', 'exam-prefix-score-accumulator', 'EASY', 'At Sarhad College, compute the optimal configuration for **Exam Prefix Score Accumulator**. Given $N$ input records, write an algorithm using Prefix Sum to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000054', 'CC054: Sliding Window Campus Wifi Usage', 'sliding-window-campus-wifi-usage', 'EASY', 'At Sarhad College, compute the optimal configuration for **Sliding Window Campus Wifi Usage**. Given $N$ input records, write an algorithm using Sliding Window to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000055', 'CC055: Lab Equipment Borrow Stack', 'lab-equipment-borrow-stack', 'EASY', 'At Sarhad College, compute the optimal configuration for **Lab Equipment Borrow Stack**. Given $N$ input records, write an algorithm using Stack to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000056', 'CC056: Canteen Orders Processing Queue', 'canteen-orders-processing-queue', 'EASY', 'At Sarhad College, compute the optimal configuration for **Canteen Orders Processing Queue**. Given $N$ input records, write an algorithm using Queue to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000057', 'CC057: Student ID Linked List Reversal', 'student-id-linked-list-reversal', 'EASY', 'At Sarhad College, compute the optimal configuration for **Student ID Linked List Reversal**. Given $N$ input records, write an algorithm using Linked List to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000058', 'CC058: Recursive Factorial Event Counter', 'recursive-factorial-event-counter', 'EASY', 'At Sarhad College, compute the optimal configuration for **Recursive Factorial Event Counter**. Given $N$ input records, write an algorithm using Recursion to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000059', 'CC059: Campus Energy Conservation Greedy', 'campus-energy-conservation-greedy', 'EASY', 'At Sarhad College, compute the optimal configuration for **Campus Energy Conservation Greedy**. Given $N$ input records, write an algorithm using Basic Greedy to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000060', 'CC060: Inter-College Debate Hash Search', 'inter-college-debate-hash-search', 'EASY', 'At Sarhad College, compute the optimal configuration for **Inter-College Debate Hash Search**. Given $N$ input records, write an algorithm using Hash Maps (Intermediate) to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000061', 'CC061: Binary Search Exam Roll Matcher', 'binary-search-exam-roll-matcher', 'EASY', 'At Sarhad College, compute the optimal configuration for **Binary Search Exam Roll Matcher**. Given $N$ input records, write an algorithm using Binary Search to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000062', 'CC062: QuickSort Placement Percentile Ranker', 'quicksort-placement-percentile-ranker', 'EASY', 'At Sarhad College, compute the optimal configuration for **QuickSort Placement Percentile Ranker**. Given $N$ input records, write an algorithm using Sorting to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000063', 'CC063: Subarray Prefix Sum Balance', 'subarray-prefix-sum-balance', 'EASY', 'At Sarhad College, compute the optimal configuration for **Subarray Prefix Sum Balance**. Given $N$ input records, write an algorithm using Prefix Sum to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000064', 'CC064: Sliding Window Highest GPA Detector', 'sliding-window-highest-gpa-detector', 'EASY', 'At Sarhad College, compute the optimal configuration for **Sliding Window Highest GPA Detector**. Given $N$ input records, write an algorithm using Sliding Window to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000065', 'CC065: Syntax Parenthesis Checker Stack', 'syntax-parenthesis-checker-stack', 'EASY', 'At Sarhad College, compute the optimal configuration for **Syntax Parenthesis Checker Stack**. Given $N$ input records, write an algorithm using Stack to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000066', 'CC066: Printer Job Emergency Queue', 'printer-job-emergency-queue', 'EASY', 'At Sarhad College, compute the optimal configuration for **Printer Job Emergency Queue**. Given $N$ input records, write an algorithm using Queue to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000067', 'CC067: Linked List Middle Student Finder', 'linked-list-middle-student-finder', 'EASY', 'At Sarhad College, compute the optimal configuration for **Linked List Middle Student Finder**. Given $N$ input records, write an algorithm using Linked List to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000068', 'CC068: Recursive Fibonaccian Seating Arrangement', 'recursive-fibonaccian-seating-arrangement', 'EASY', 'At Sarhad College, compute the optimal configuration for **Recursive Fibonaccian Seating Arrangement**. Given $N$ input records, write an algorithm using Recursion to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000069', 'CC069: Greedy Campus Festival Booth Allocator', 'greedy-campus-festival-booth-allocator', 'EASY', 'At Sarhad College, compute the optimal configuration for **Greedy Campus Festival Booth Allocator**. Given $N$ input records, write an algorithm using Basic Greedy to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000070', 'CC070: Hash Map Student Pair Matcher', 'hash-map-student-pair-matcher', 'EASY', 'At Sarhad College, compute the optimal configuration for **Hash Map Student Pair Matcher**. Given $N$ input records, write an algorithm using Hash Maps (Intermediate) to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000071', 'CC071: Binary Search Rotated Library Shelf', 'binary-search-rotated-library-shelf', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Binary Search Rotated Library Shelf**. Given $N$ input records, write an algorithm using Binary Search to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000072', 'CC072: MergeSort Grade Rank Sorting', 'mergesort-grade-rank-sorting', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **MergeSort Grade Rank Sorting**. Given $N$ input records, write an algorithm using Sorting to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000073', 'CC073: Prefix Sum Attendance Target Reach', 'prefix-sum-attendance-target-reach', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Prefix Sum Attendance Target Reach**. Given $N$ input records, write an algorithm using Prefix Sum to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000074', 'CC074: Max Sum Subarray Sliding Window', 'max-sum-subarray-sliding-window', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Max Sum Subarray Sliding Window**. Given $N$ input records, write an algorithm using Sliding Window to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000075', 'CC075: Evaluate Reverse Polish Notation Stack', 'evaluate-reverse-polish-notation-stack', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Evaluate Reverse Polish Notation Stack**. Given $N$ input records, write an algorithm using Stack to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000076', 'CC076: Recent Student Logins Queue', 'recent-student-logins-queue', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Recent Student Logins Queue**. Given $N$ input records, write an algorithm using Queue to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000077', 'CC077: Cycle Detection in Student Referral List', 'cycle-detection-in-student-referral-list', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Cycle Detection in Student Referral List**. Given $N$ input records, write an algorithm using Linked List to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000078', 'CC078: Recursive Tower of Brahma Placement Puzzle', 'recursive-tower-of-brahma-placement-puzzle', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Recursive Tower of Brahma Placement Puzzle**. Given $N$ input records, write an algorithm using Recursion to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000079', 'CC079: Greedy Activity Selector for Auditorium', 'greedy-activity-selector-for-auditorium', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Greedy Activity Selector for Auditorium**. Given $N$ input records, write an algorithm using Basic Greedy to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000080', 'CC080: Hash Map Frequency Ranker', 'hash-map-frequency-ranker', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Hash Map Frequency Ranker**. Given $N$ input records, write an algorithm using Hash Maps (Intermediate) to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000081', 'CC081: Binary Search Matrix Seat Finder', 'binary-search-matrix-seat-finder', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Binary Search Matrix Seat Finder**. Given $N$ input records, write an algorithm using Binary Search to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000082', 'CC082: Custom TimSort Student Ranking', 'custom-timsort-student-ranking', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Custom TimSort Student Ranking**. Given $N$ input records, write an algorithm using Sorting to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000083', 'CC083: 2D Range Sum Query Matrix', '2d-range-sum-query-matrix', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **2D Range Sum Query Matrix**. Given $N$ input records, write an algorithm using Prefix Sum to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000084', 'CC084: Longest Substring K Distinct Characters', 'longest-substring-k-distinct-characters', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Longest Substring K Distinct Characters**. Given $N$ input records, write an algorithm using Sliding Window to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000085', 'CC085: Monotonic Stack Next Greater Grade', 'monotonic-stack-next-greater-grade', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Monotonic Stack Next Greater Grade**. Given $N$ input records, write an algorithm using Stack to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000086', 'CC086: Circular Queue Hostel Gate Scanner', 'circular-queue-hostel-gate-scanner', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Circular Queue Hostel Gate Scanner**. Given $N$ input records, write an algorithm using Queue to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000087', 'CC087: Remove Nth Node Student Linked List', 'remove-nth-node-student-linked-list', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Remove Nth Node Student Linked List**. Given $N$ input records, write an algorithm using Linked List to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000088', 'CC088: Recursive Combination Generator', 'recursive-combination-generator', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Recursive Combination Generator**. Given $N$ input records, write an algorithm using Recursion to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000089', 'CC089: Min Coins Campus Canteen Cashback', 'min-coins-campus-canteen-cashback', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Min Coins Campus Canteen Cashback**. Given $N$ input records, write an algorithm using Basic Greedy to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000090', 'CC090: Hash Map Anagram Student Names', 'hash-map-anagram-student-names', 'MEDIUM', 'At Sarhad College, compute the optimal configuration for **Hash Map Anagram Student Names**. Given $N$ input records, write an algorithm using Hash Maps (Intermediate) to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000091', 'CC091: Binary Search Peak Score Finding', 'binary-search-peak-score-finding', 'HARD', 'At Sarhad College, compute the optimal configuration for **Binary Search Peak Score Finding**. Given $N$ input records, write an algorithm using Binary Search to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000092', 'CC092: Stable Sort Placement Applications', 'stable-sort-placement-applications', 'HARD', 'At Sarhad College, compute the optimal configuration for **Stable Sort Placement Applications**. Given $N$ input records, write an algorithm using Sorting to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000093', 'CC093: Continuous Subarray Sum Prefix', 'continuous-subarray-sum-prefix', 'HARD', 'At Sarhad College, compute the optimal configuration for **Continuous Subarray Sum Prefix**. Given $N$ input records, write an algorithm using Prefix Sum to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000094', 'CC094: Sliding Window Fruit Collector', 'sliding-window-fruit-collector', 'HARD', 'At Sarhad College, compute the optimal configuration for **Sliding Window Fruit Collector**. Given $N$ input records, write an algorithm using Sliding Window to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000095', 'CC095: Stock Span Calculator Stack', 'stock-span-calculator-stack', 'HARD', 'At Sarhad College, compute the optimal configuration for **Stock Span Calculator Stack**. Given $N$ input records, write an algorithm using Stack to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000096', 'CC096: Queue Reconstruction by Height', 'queue-reconstruction-by-height', 'HARD', 'At Sarhad College, compute the optimal configuration for **Queue Reconstruction by Height**. Given $N$ input records, write an algorithm using Queue to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000097', 'CC097: Merge Two Sorted Student Lists', 'merge-two-sorted-student-lists', 'HARD', 'At Sarhad College, compute the optimal configuration for **Merge Two Sorted Student Lists**. Given $N$ input records, write an algorithm using Linked List to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000098', 'CC098: Recursive Permutation Seating Arrangement', 'recursive-permutation-seating-arrangement', 'HARD', 'At Sarhad College, compute the optimal configuration for **Recursive Permutation Seating Arrangement**. Given $N$ input records, write an algorithm using Recursion to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000099', 'CC099: Gas Station Loop Greedy Route', 'gas-station-loop-greedy-route', 'HARD', 'At Sarhad College, compute the optimal configuration for **Gas Station Loop Greedy Route**. Given $N$ input records, write an algorithm using Basic Greedy to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000100', 'CC100: Group Anagram Student Clubs Hash Map', 'group-anagram-student-clubs-hash-map', 'HARD', 'At Sarhad College, compute the optimal configuration for **Group Anagram Student Clubs Hash Map**. Given $N$ input records, write an algorithm using Hash Maps (Intermediate) to process student records efficiently.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
