-- CampusCode Original Problem Set (CCPS v1.0) - Batch 1 (CC001 - CC050)

INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000001', 'CC001: Campus Cafeteria Billing System', 'campus-cafeteria-billing-system', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Cafeteria Billing System** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000002', 'CC002: Library Book Stacking Order', 'library-book-stacking-order', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Library Book Stacking Order** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000003', 'CC003: Campus Bus Seat Reservation', 'campus-bus-seat-reservation', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Bus Seat Reservation** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000004', 'CC004: Student ID Hash Verifier', 'student-id-hash-verifier', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student ID Hash Verifier** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000005', 'CC005: Hostel Room Allocation Preference', 'hostel-room-allocation-preference', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Hostel Room Allocation Preference** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000006', 'CC006: Semester GPA Percentile Ranker', 'semester-gpa-percentile-ranker', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Semester GPA Percentile Ranker** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000007', 'CC007: Exam Hall Seating Plan', 'exam-hall-seating-plan', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Exam Hall Seating Plan** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000008', 'CC008: Campus Wi-Fi Bandwidth Balancer', 'campus-wi-fi-bandwidth-balancer', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Wi-Fi Bandwidth Balancer** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000009', 'CC009: Placement Offer Salary Sorter', 'placement-offer-salary-sorter', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Placement Offer Salary Sorter** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000010', 'CC010: Lab Equipment Inventory Check', 'lab-equipment-inventory-check', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Lab Equipment Inventory Check** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000011', 'CC011: College Event Ticket Reservation', 'college-event-ticket-reservation', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **College Event Ticket Reservation** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000012', 'CC012: Department Library Catalog Search', 'department-library-catalog-search', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Department Library Catalog Search** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000013', 'CC013: Student Attendance Streak Counter', 'student-attendance-streak-counter', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Attendance Streak Counter** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000014', 'CC014: Canteen Discount Combo Finder', 'canteen-discount-combo-finder', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Canteen Discount Combo Finder** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000015', 'CC015: Classroom Projector Assignment', 'classroom-projector-assignment', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Classroom Projector Assignment** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000016', 'CC016: Campus Shuttle Frequency Analyzer', 'campus-shuttle-frequency-analyzer', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Shuttle Frequency Analyzer** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000017', 'CC017: Sports Meet Medals Tally', 'sports-meet-medals-tally', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Sports Meet Medals Tally** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000018', 'CC018: Coding Club Pair Programming Matching', 'coding-club-pair-programming-matching', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Coding Club Pair Programming Matching** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000019', 'CC019: Campus Gate Entry Logging', 'campus-gate-entry-logging', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Gate Entry Logging** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000020', 'CC020: Faculty Lecture Slot Scheduler', 'faculty-lecture-slot-scheduler', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Faculty Lecture Slot Scheduler** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000021', 'CC021: Library Overdue Fine Calculator', 'library-overdue-fine-calculator', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Library Overdue Fine Calculator** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000022', 'CC022: Student Project Repository Search', 'student-project-repository-search', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Project Repository Search** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000023', 'CC023: Campus Canteen Token Dispenser', 'campus-canteen-token-dispenser', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Canteen Token Dispenser** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000024', 'CC024: Hostel Laundry Machine Queue', 'hostel-laundry-machine-queue', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **Hostel Laundry Machine Queue** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000025', 'CC025: College Fest Main Stage Schedule', 'college-fest-main-stage-schedule', 'EASY', 'In Sarhad College Campus, the administration requires an automated solution to solve **College Fest Main Stage Schedule** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000026', 'CC026: Robotics Club Component Inventory', 'robotics-club-component-inventory', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Robotics Club Component Inventory** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000027', 'CC027: Placement Resume Keyword Scanner', 'placement-resume-keyword-scanner', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Placement Resume Keyword Scanner** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000028', 'CC028: Alumni Donation Target Tracker', 'alumni-donation-target-tracker', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Alumni Donation Target Tracker** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000029', 'CC029: Campus Cafeteria Calorie Meter', 'campus-cafeteria-calorie-meter', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Cafeteria Calorie Meter** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000030', 'CC030: Student Grade Point Boundary Calculator', 'student-grade-point-boundary-calculator', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Grade Point Boundary Calculator** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000031', 'CC031: Library Rare Books Access Audit', 'library-rare-books-access-audit', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Library Rare Books Access Audit** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000032', 'CC032: Campus Bus Route Optimization', 'campus-bus-route-optimization', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Bus Route Optimization** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000033', 'CC033: Hostel Mess Weekly Menu Planner', 'hostel-mess-weekly-menu-planner', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Hostel Mess Weekly Menu Planner** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000034', 'CC034: Semester Exam Retake Fee Calculator', 'semester-exam-retake-fee-calculator', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Semester Exam Retake Fee Calculator** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000035', 'CC035: Student Hackathon Team Builder', 'student-hackathon-team-builder', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Hackathon Team Builder** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000036', 'CC036: Campus Parking Slot Allocator', 'campus-parking-slot-allocator', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Parking Slot Allocator** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000037', 'CC037: Department HOD Notice Distribution', 'department-hod-notice-distribution', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Department HOD Notice Distribution** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000038', 'CC038: College Library Card Renewal Check', 'college-library-card-renewal-check', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **College Library Card Renewal Check** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000039', 'CC039: Student Gym Equipment Reservation', 'student-gym-equipment-reservation', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Gym Equipment Reservation** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000040', 'CC040: Campus Green Energy Monitor', 'campus-green-energy-monitor', 'MEDIUM', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Green Energy Monitor** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000041', 'CC041: placement Mock Interview Slotting', 'placement-mock-interview-slotting', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **placement Mock Interview Slotting** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000042', 'CC042: Student Transcript GPA Averager', 'student-transcript-gpa-averager', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Transcript GPA Averager** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000043', 'CC043: College Magazine Article Review', 'college-magazine-article-review', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **College Magazine Article Review** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000044', 'CC044: Hostel Visitor Entry Timestamp Audit', 'hostel-visitor-entry-timestamp-audit', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Hostel Visitor Entry Timestamp Audit** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000045', 'CC045: Campus Shuttle Battery Charging Schedule', 'campus-shuttle-battery-charging-schedule', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Shuttle Battery Charging Schedule** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000046', 'CC046: Library Computer Lab Seat Booking', 'library-computer-lab-seat-booking', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Library Computer Lab Seat Booking** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000047', 'CC047: Student Club Budget Expense Tracker', 'student-club-budget-expense-tracker', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Student Club Budget Expense Tracker** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000048', 'CC048: Campus Auditorium Light Show Cue', 'campus-auditorium-light-show-cue', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Auditorium Light Show Cue** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000049', 'CC049: Placement Drive Aptitude Test Timer', 'placement-drive-aptitude-test-timer', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Placement Drive Aptitude Test Timer** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.problems (id, title, slug, difficulty, description, constraints, status) VALUES ('10000000-0000-4000-8000-000000000050', 'CC050: Campus Code Official Leaderboard Refresh', 'campus-code-official-leaderboard-refresh', 'HARD', 'In Sarhad College Campus, the administration requires an automated solution to solve **Campus Code Official Leaderboard Refresh** efficiently. Given an array of student activity records, calculate the optimal configuration.', '1 <= N <= 10^5
-10^9 <= A[i] <= 10^9', 'published') ON CONFLICT (id) DO NOTHING;
